export const AIRPORT_DATA = [
  { iata: 'ATL', icao: 'KATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', country: 'United States', lat: 33.6407, lon: -84.4277 },
  { iata: 'DXB', icao: 'OMDB', name: 'Dubai International Airport', city: 'Dubai', country: 'United Arab Emirates', lat: 25.2532, lon: 55.3657 },
  { iata: 'LDY', icao: 'EGAE', name: 'City of Derry Airport', city: 'Derry/Londonderry', country: 'United Kingdom', lat: 55.0397, lon: 7.1558 },
  { iata: 'NCL', icao: 'EGNT', name: 'Newcastle International Airport', city: 'Newcastle Upon Tyne', country: 'United Kingdom', lat: 55.0393, lon: 1.6931},
  { iata: 'DFW', icao: 'KDFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', country: 'United States', lat: 32.8998, lon: -97.0403 },
  { iata: 'LHR', icao: 'EGLL', name: 'London Heathrow Airport', city: 'London', country: 'United Kingdom', lat: 51.4700, lon: -0.4543 },
  { iata: 'HND', icao: 'RJTT', name: 'Tokyo Haneda Airport', city: 'Tokyo', country: 'Japan', lat: 35.5494, lon: 139.7798 },
  { iata: 'DEN', icao: 'KDEN', name: 'Denver International Airport', city: 'Denver', country: 'United States', lat: 39.8561, lon: -104.6737 },
  { iata: 'IST', icao: 'LTFM', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey', lat: 41.2753, lon: 28.7519 },
  { iata: 'LAX', icao: 'KLAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'United States', lat: 33.9416, lon: -118.4085 },
  { iata: 'ORD', icao: 'KORD', name: "O'Hare International Airport", city: 'Chicago', country: 'United States', lat: 41.9742, lon: -87.9073 },
  { iata: 'DEL', icao: 'VIDP', name: 'Indira Gandhi International Airport', city: 'Delhi', country: 'India', lat: 28.5562, lon: 77.1000 },
  { iata: 'CDG', icao: 'LFPG', name: 'Charles de Gaulle Airport', city: 'Paris', country: 'France', lat: 49.0097, lon: 2.5479 },
  { iata: 'CAN', icao: 'ZGGG', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou', country: 'China', lat: 23.3924, lon: 113.2988 },
  { iata: 'JFK', icao: 'KJFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'United States', lat: 40.6413, lon: -73.7781 },
  { iata: 'AMS', icao: 'EHAM', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam', country: 'Netherlands', lat: 52.3105, lon: 4.7683 },
  { iata: 'MAD', icao: 'LEMD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid', country: 'Spain', lat: 40.4983, lon: -3.5676 },
  { iata: 'FRA', icao: 'EDDF', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany', lat: 50.0379, lon: 8.5622 },
  { iata: 'MCO', icao: 'KMCO', name: 'Orlando International Airport', city: 'Orlando', country: 'United States', lat: 28.4312, lon: -81.3081 },
  { iata: 'LAS', icao: 'KLAS', name: 'Harry Reid International Airport', city: 'Las Vegas', country: 'United States', lat: 36.0840, lon: -115.1537 },
  { iata: 'CLT', icao: 'KCLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', country: 'United States', lat: 35.2140, lon: -80.9431 },
  { iata: 'MIA', icao: 'KMIA', name: 'Miami International Airport', city: 'Miami', country: 'United States', lat: 25.7959, lon: -80.2871 },
  { iata: 'SEA', icao: 'KSEA', name: 'Seattle–Tacoma International Airport', city: 'Seattle', country: 'United States', lat: 47.4502, lon: -122.3088 },
  { iata: 'PHX', icao: 'KPHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', country: 'United States', lat: 33.4343, lon: -112.0116 },
  { iata: 'EWR', icao: 'KEWR', name: 'Newark Liberty International Airport', city: 'Newark', country: 'United States', lat: 40.6925, lon: -74.1687 },
  { iata: 'SFO', icao: 'KSFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'United States', lat: 37.6213, lon: -122.3790 },
  { iata: 'BKK', icao: 'VTBS', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand', lat: 13.6900, lon: 100.7501 },
  { iata: 'ICN', icao: 'RKSI', name: 'Incheon International Airport', city: 'Seoul', country: 'South Korea', lat: 37.4602, lon: 126.4407 },
  { iata: 'SIN', icao: 'WSSS', name: 'Singapore Changi Airport', city: 'Singapore', country: 'Singapore', lat: 1.3644, lon: 103.9915 },
  { iata: 'IAH', icao: 'KIAH', name: 'George Bush Intercontinental Airport', city: 'Houston', country: 'United States', lat: 29.9902, lon: -95.3368 },
  { iata: 'BOS', icao: 'KBOS', name: 'Logan International Airport', city: 'Boston', country: 'United States', lat: 42.3656, lon: -71.0096 },
  { iata: 'FCO', icao: 'LIRF', name: 'Leonardo da Vinci–Fiumicino Airport', city: 'Rome', country: 'Italy', lat: 41.8003, lon: 12.2389 },
  { iata: 'PVG', icao: 'ZSPD', name: 'Shanghai Pudong International Airport', city: 'Shanghai', country: 'China', lat: 31.1434, lon: 121.8053 },
  { iata: 'YYZ', icao: 'CYYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada', lat: 43.6777, lon: -79.6248 },
  { iata: 'LGW', icao: 'EGKK', name: 'Gatwick Airport', city: 'London', country: 'United Kingdom', lat: 51.1537, lon: -0.1821 },
  { iata: 'MUC', icao: 'EDDM', name: 'Munich Airport', city: 'Munich', country: 'Germany', lat: 48.3537, lon: 11.7861 },
  { iata: 'SYD', icao: 'YSSY', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', country: 'Australia', lat: -33.9479, lon: 151.1793 },
  { iata: 'BCN', icao: 'LEBL', name: 'Josep Tarradellas Barcelona–El Prat Airport', city: 'Barcelona', country: 'Spain', lat: 41.2974, lon: 2.0833 },
  { iata: 'MSP', icao: 'KMSP', name: 'Minneapolis–Saint Paul International Airport', city: 'Minneapolis', country: 'United States', lat: 44.8848, lon: -93.2223 },
  { iata: 'DTW', icao: 'KDTW', name: 'Detroit Metropolitan Airport', city: 'Detroit', country: 'United States', lat: 42.2162, lon: -83.3554 },
  { iata: 'FLL', icao: 'KFLL', name: 'Fort Lauderdale–Hollywood International Airport', city: 'Fort Lauderdale', country: 'United States', lat: 26.0726, lon: -80.1527 },
  { iata: 'LGA', icao: 'KLGA', name: 'LaGuardia Airport', city: 'New York', country: 'United States', lat: 40.7769, lon: -73.8740 },
  { iata: 'SLC', icao: 'KSLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', country: 'United States', lat: 40.7899, lon: -111.9791 },
  { iata: 'PHL', icao: 'KPHL', name: 'Philadelphia International Airport', city: 'Philadelphia', country: 'United States', lat: 39.8722, lon: -75.2424 },
  { iata: 'BWI', icao: 'KBWI', name: 'Baltimore/Washington International Thurgood Marshall Airport', city: 'Baltimore', country: 'United States', lat: 39.1774, lon: -76.6684 },
  { iata: 'DCA', icao: 'KDCA', name: 'Ronald Reagan Washington National Airport', city: 'Arlington', country: 'United States', lat: 38.8512, lon: -77.0402 },
  { iata: 'IAD', icao: 'KIAD', name: 'Dulles International Airport', city: 'Dulles', country: 'United States', lat: 38.9531, lon: -77.4565 },
  { iata: 'SAN', icao: 'KSAN', name: 'San Diego International Airport', city: 'San Diego', country: 'United States', lat: 32.7338, lon: -117.1933 },
  { iata: 'TPA', icao: 'KTPA', name: 'Tampa International Airport', city: 'Tampa', country: 'United States', lat: 27.9799, lon: -82.5324 },
  { iata: 'MEX', icao: 'MMMX', name: 'Mexico City International Airport', city: 'Mexico City', country: 'Mexico', lat: 19.4363, lon: -99.0721 },
  { iata: 'DUB', icao: 'EIDW', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland', lat: 53.4264, lon: -6.2499 },
  { iata: 'ZRH', icao: 'LSZH', name: 'Zurich Airport', city: 'Zürich', country: 'Switzerland', lat: 47.4647, lon: 8.5492 },
  { iata: 'VIE', icao: 'LOWW', name: 'Vienna International Airport', city: 'Vienna', country: 'Austria', lat: 48.1103, lon: 16.5697 },
  { iata: 'HKG', icao: 'VHHH', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'Hong Kong', lat: 22.3080, lon: 113.9185 },
  { iata: 'NRT', icao: 'RJAA', name: 'Narita International Airport', city: 'Tokyo', country: 'Japan', lat: 35.7720, lon: 140.3929 },
  { iata: 'JNB', icao: 'FAOR', name: 'O. R. Tambo International Airport', city: 'Johannesburg', country: 'South Africa', lat: -26.1367, lon: 28.2411 },
  { iata: 'GRU', icao: 'SBGR', name: 'São Paulo/Guarulhos–Governador André Franco Montoro International Airport', city: 'São Paulo', country: 'Brazil', lat: -23.4356, lon: -46.4731 },
  { iata: 'SCL', icao: 'SCEL', name: 'Arturo Merino Benítez International Airport', city: 'Santiago', country: 'Chile', lat: -33.3930, lon: -70.7858 },
  { iata: 'BOG', icao: 'SKBO', name: 'El Dorado International Airport', city: 'Bogotá', country: 'Colombia', lat: 4.7016, lon: -74.1469 },
  { iata: 'LIM', icao: 'SPJC', name: 'Jorge Chávez International Airport', city: 'Lima', country: 'Peru', lat: -12.0219, lon: -77.1143 },
  { iata: 'EZE', icao: 'SAEZ', name: 'Ministro Pistarini International Airport', city: 'Buenos Aires', country: 'Argentina', lat: -34.8222, lon: -58.5358 },
  { iata: 'AUA', icao: 'TNCA', name: 'Queen Beatrix International Airport', city: 'Oranjestad', country: 'Aruba', lat: 12.5014, lon: -70.0152 },
  { iata: 'CUN', icao: 'MMUN', name: 'Cancún International Airport', city: 'Cancún', country: 'Mexico', lat: 21.0365, lon: -86.8771 },
  { iata: 'PUJ', icao: 'MDPC', name: 'Punta Cana International Airport', city: 'Punta Cana', country: 'Dominican Republic', lat: 18.5675, lon: -68.3633 },
  { iata: 'MBJ', icao: 'MKJS', name: 'Sangster International Airport', city: 'Montego Bay', country: 'Jamaica', lat: 18.4981, lon: -77.9184 },
  { iata: 'NAS', icao: 'MYNN', name: 'Lynden Pindling International Airport', city: 'Nassau', country: 'Bahamas', lat: 25.0389, lon: -77.4662 },
  { iata: 'GCM', icao: 'MWCR', name: 'Owen Roberts International Airport', city: 'George Town', country: 'Cayman Islands', lat: 19.2928, lon: -81.3578 },
  { iata: 'BGI', icao: 'TBPB', name: 'Grantley Adams International Airport', city: 'Bridgetown', country: 'Barbados', lat: 13.0747, lon: -59.4925 },
  { iata: 'SJU', icao: 'TJSJ', name: 'Luis Muñoz Marín International Airport', city: 'San Juan', country: 'Puerto Rico', lat: 18.4394, lon: -66.0018 },
  { iata: 'YVR', icao: 'CYVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada', lat: 49.1967, lon: -123.1815 },
  { iata: 'YYC', icao: 'CYYC', name: 'Calgary International Airport', city: 'Calgary', country: 'Canada', lat: 51.1215, lon: -114.0106 },
  { iata: 'YUL', icao: 'CYUL', name: 'Montréal–Trudeau International Airport', city: 'Montréal', country: 'Canada', lat: 45.4691, lon: -73.7434 },
  { iata: 'KEF', icao: 'BIKF', name: 'Keflavík Airport', city: 'Reykjavík', country: 'Iceland', lat: 63.9850, lon: -22.6056 },
  { iata: 'CPH', icao: 'EKCH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark', lat: 55.6180, lon: 12.6508 },
  { iata: 'OSL', icao: 'ENGM', name: 'Oslo Airport, Gardermoen', city: 'Oslo', country: 'Norway', lat: 60.1976, lon: 11.1004 },
  { iata: 'ARN', icao: 'ESSA', name: 'Stockholm Arlanda Airport', city: 'Stockholm', country: 'Sweden', lat: 59.6519, lon: 17.9186 },
  { iata: 'HEL', icao: 'EFHK', name: 'Helsinki-Vantaa Airport', city: 'Helsinki', country: 'Finland', lat: 60.3172, lon: 24.9633 },
  { iata: 'WAW', icao: 'EPWA', name: 'Warsaw Chopin Airport', city: 'Warsaw', country: 'Poland', lat: 52.1657, lon: 20.9671 },
  { iata: 'PRG', icao: 'LKPR', name: 'Václav Havel Airport Prague', city: 'Prague', country: 'Czech Republic', lat: 50.1008, lon: 14.2600 },
  { iata: 'BUD', icao: 'LHBP', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', country: 'Hungary', lat: 47.4399, lon: 19.2556 },
  { iata: 'ATH', icao: 'LGAV', name: 'Athens International Airport', city: 'Athens', country: 'Greece', lat: 37.9364, lon: 23.9444 },
  { iata: 'LIS', icao: 'LPPT', name: 'Humberto Delgado Airport', city: 'Lisbon', country: 'Portugal', lat: 38.7742, lon: -9.1342 },
  { iata: 'BRU', icao: 'EBBR', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium', lat: 50.9014, lon: 4.4844 },
  { iata: 'GVA', icao: 'LSGG', name: 'Geneva Airport', city: 'Geneva', country: 'Switzerland', lat: 46.2381, lon: 6.1089 },
  { iata: 'OTP', icao: 'LROP', name: 'Henri Coandă International Airport', city: 'Bucharest', country: 'Romania', lat: 44.5711, lon: 26.0858 },
  { iata: 'CAI', icao: 'HECA', name: 'Cairo International Airport', city: 'Cairo', country: 'Egypt', lat: 30.1219, lon: 31.4056 },
  { iata: 'DOH', icao: 'OTHH', name: 'Hamad International Airport', city: 'Doha', country: 'Qatar', lat: 25.2731, lon: 51.6081 },
  { iata: 'AUH', icao: 'OMAA', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi', country: 'United Arab Emirates', lat: 24.4330, lon: 54.6511 },
  { iata: 'JED', icao: 'OEJN', name: 'King Abdulaziz International Airport', city: 'Jeddah', country: 'Saudi Arabia', lat: 21.6796, lon: 39.1565 },
  { iata: 'RUH', icao: 'OERK', name: 'King Khalid International Airport', city: 'Riyadh', country: 'Saudi Arabia', lat: 24.9576, lon: 46.6988 },
  { iata: 'KUL', icao: 'WMKK', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', country: 'Malaysia', lat: 2.7456, lon: 101.7099 },
  { iata: 'MNL', icao: 'RPLL', name: 'Ninoy Aquino International Airport', city: 'Manila', country: 'Philippines', lat: 14.5086, lon: 121.0194 },
  { iata: 'CGK', icao: 'WIII', name: 'Soekarno–Hatta International Airport', city: 'Jakarta', country: 'Indonesia', lat: -6.1256, lon: 106.6559 },
  { iata: 'SGN', icao: 'VVTS', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City', country: 'Vietnam', lat: 10.8189, lon: 106.6519 },
  { iata: 'BOM', icao: 'VABB', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'India', lat: 19.0896, lon: 72.8656 },
  { iata: 'PEK', icao: 'ZBAA', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China', lat: 40.0801, lon: 116.5845 },
  { iata: 'MEL', icao: 'YMML', name: 'Melbourne Airport', city: 'Melbourne', country: 'Australia', lat: -37.6690, lon: 144.8410 },
  { iata: 'AKL', icao: 'NZAA', name: 'Auckland Airport', city: 'Auckland', country: 'New Zealand', lat: -37.0082, lon: 174.7917 },
  { iata: 'CPT', icao: 'FACT', name: 'Cape Town International Airport', city: 'Cape Town', country: 'South Africa', lat: -33.9715, lon: 18.6021 },
  { iata: 'LOS', icao: 'DNMM', name: 'Murtala Muhammed International Airport', city: 'Lagos', country: 'Nigeria', lat: 6.5774, lon: 3.3211 },
  { iata: 'NBO', icao: 'HKJK', name: 'Jomo Kenyatta International Airport', city: 'Nairobi', country: 'Kenya', lat: -1.3192, lon: 36.9278 },
  { iata: 'ADD', icao: 'HAAB', name: 'Bole International Airport', city: 'Addis Ababa', country: 'Ethiopia', lat: 8.9779, lon: 38.7993 },
  { iata: 'CMN', icao: 'GMMN', name: 'Mohammed V International Airport', city: 'Casablanca', country: 'Morocco', lat: 33.3675, lon: -7.5899 },
  { iata: 'ALG', icao: 'DAAG', name: 'Houari Boumediene Airport', city: 'Algiers', country: 'Algeria', lat: 36.6910, lon: 3.2154 },
  { iata: 'TUN', icao: 'DTTA', name: 'Tunis–Carthage Airport', city: 'Tunis', country: 'Tunisia', lat: 36.8510, lon: 10.2272 },
  { iata: 'TLV', icao: 'LLBG', name: 'Ben Gurion Airport', city: 'Tel Aviv', country: 'Israel', lat: 32.0095, lon: 34.8854 },
  { iata: 'AMM', icao: 'OJAI', name: 'Queen Alia International Airport', city: 'Amman', country: 'Jordan', lat: 31.7226, lon: 35.9932 },
  { iata: 'BEY', icao: 'OLBA', name: 'Beirut–Rafic Hariri International Airport', city: 'Beirut', country: 'Lebanon', lat: 33.8209, lon: 35.4884 },
  { iata: 'KWI', icao: 'OKBK', name: 'Kuwait International Airport', city: 'Kuwait City', country: 'Kuwait', lat: 29.2266, lon: 47.9689 },
  { iata: 'BAH', icao: 'OBBI', name: 'Bahrain International Airport', city: 'Manama', country: 'Bahrain', lat: 26.2708, lon: 50.6336 },
  { iata: 'MCT', icao: 'OOMS', name: 'Muscat International Airport', city: 'Muscat', country: 'Oman', lat: 23.5933, lon: 58.2844 },
  { iata: 'ALA', icao: 'UAAA', name: 'Almaty International Airport', city: 'Almaty', country: 'Kazakhstan', lat: 43.3521, lon: 77.0405 },
  { iata: 'TAS', icao: 'UTTT', name: 'Tashkent International Airport', city: 'Tashkent', country: 'Uzbekistan', lat: 41.2575, lon: 69.2811 },
  { iata: 'GYD', icao: 'UBBB', name: 'Heydar Aliyev International Airport', city: 'Baku', country: 'Azerbaijan', lat: 40.4675, lon: 50.0467 },
  { iata: 'EVN', icao: 'UDYZ', name: 'Zvartnots International Airport', city: 'Yerevan', country: 'Armenia', lat: 40.1473, lon: 44.3959 },
  { iata: 'TBS', icao: 'UGTB', name: 'Tbilisi International Airport', city: 'Tbilisi', country: 'Georgia', lat: 41.6692, lon: 44.9547 },
  { iata: 'KBP', icao: 'UKBB', name: 'Boryspil International Airport', city: 'Kyiv', country: 'Ukraine', lat: 50.3450, lon: 30.8947 },
  { iata: 'MSQ', icao: 'UMMS', name: 'Minsk National Airport', city: 'Minsk', country: 'Belarus', lat: 53.8824, lon: 28.0307 },
  { iata: 'RIX', icao: 'EVRA', name: 'Riga International Airport', city: 'Riga', country: 'Latvia', lat: 56.9236, lon: 23.9711 },
  { iata: 'VNO', icao: 'EYVI', name: 'Vilnius Airport', city: 'Vilnius', country: 'Lithuania', lat: 54.6341, lon: 25.2858 },
  { iata: 'TLL', icao: 'EETN', name: 'Tallinn Airport', city: 'Tallinn', country: 'Estonia', lat: 59.4133, lon: 24.8328 },
  { iata: 'SVO', icao: 'UUEE', name: 'Sheremetyevo International Airport', city: 'Moscow', country: 'Russia', lat: 55.9726, lon: 37.4146 },
  { iata: 'DME', icao: 'UUDD', name: 'Domodedovo International Airport', city: 'Moscow', country: 'Russia', lat: 55.4088, lon: 37.9063 },
  { iata: 'LED', icao: 'ULLI', name: 'Pulkovo Airport', city: 'Saint Petersburg', country: 'Russia', lat: 59.8003, lon: 30.2625 },
  { iata: 'HNL', icao: 'PHNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', country: 'United States', lat: 21.324, lon: -157.922 },
  { iata: 'ANC', icao: 'PANC', name: 'Ted Stevens Anchorage International Airport', city: 'Anchorage', country: 'United States', lat: 61.174, lon: -149.996 },
  { iata: 'FAI', icao: 'PAFA', name: 'Fairbanks International Airport', city: 'Fairbanks', country: 'United States', lat: 64.815, lon: -147.856 },
  { iata: 'OGG', icao: 'PHOG', name: 'Kahului Airport', city: 'Kahului', country: 'United States', lat: 20.898, lon: -156.430 },
  { iata: 'KOA', icao: 'PHKO', name: 'Kona International Airport', city: 'Kailua-Kona', country: 'United States', lat: 19.738, lon: -156.045 },
  { iata: 'LIH', icao: 'PHLI', name: 'Lihue Airport', city: 'Lihue', country: 'United States', lat: 21.976, lon: -159.339 },
  { iata: 'PPT', icao: 'NTAA', name: "Faa'a International Airport", city: 'Papeete', country: 'French Polynesia', lat: -17.556, lon: -149.611 },
  { iata: 'NAN', icao: 'NFFN', name: 'Nadi International Airport', city: 'Nadi', country: 'Fiji', lat: -17.755, lon: 177.443 },
  { iata: 'GUM', icao: 'PGUM', name: 'Antonio B. Won Pat International Airport', city: 'Hagåtña', country: 'Guam', lat: 13.483, lon: 144.796 },
  { iata: 'MDW', icao: 'KMDW', name: 'Midway International Airport', city: 'Chicago', country: 'United States', lat: 41.786, lon: -87.752 },
  { iata: 'DAL', icao: 'KDAL', name: 'Dallas Love Field', city: 'Dallas', country: 'United States', lat: 32.847, lon: -96.851 },
  { iata: 'HOU', icao: 'KHOU', name: 'William P. Hobby Airport', city: 'Houston', country: 'United States', lat: 29.645, lon: -95.278 },
  { iata: 'OAK', icao: 'KOAK', name: 'Oakland International Airport', city: 'Oakland', country: 'United States', lat: 37.712, lon: -122.219 },
  { iata: 'SJC', icao: 'KSJC', name: 'San José Mineta International Airport', city: 'San Jose', country: 'United States', lat: 37.363, lon: -121.929 },
  { iata: 'SMF', icao: 'KSMF', name: 'Sacramento International Airport', city: 'Sacramento', country: 'United States', lat: 38.695, lon: -121.590 },
  { iata: 'PDX', icao: 'KPDX', name: 'Portland International Airport', city: 'Portland', country: 'United States', lat: 45.589, lon: -122.595 },
  { iata: 'STL', icao: 'KSTL', name: 'St. Louis Lambert International Airport', city: 'St. Louis', country: 'United States', lat: 38.748, lon: -90.370 },
  { iata: 'MCI', icao: 'KMCI', name: 'Kansas City International Airport', city: 'Kansas City', country: 'United States', lat: 39.297, lon: -94.713 },
  { iata: 'BNA', icao: 'KBNA', name: 'Nashville International Airport', city: 'Nashville', country: 'United States', lat: 36.126, lon: -86.678 },
  { iata: 'AUS', icao: 'KAUS', name: 'Austin-Bergstrom International Airport', city: 'Austin', country: 'United States', lat: 30.197, lon: -97.666 },
  { iata: 'MSY', icao: 'KMSY', name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans', country: 'United States', lat: 29.993, lon: -90.259 },
  { iata: 'RDU', icao: 'KRDU', name: 'Raleigh-Durham International Airport', city: 'Raleigh', country: 'United States', lat: 35.879, lon: -78.787 },
  { iata: 'PIT', icao: 'KPIT', name: 'Pittsburgh International Airport', city: 'Pittsburgh', country: 'United States', lat: 40.495, lon: -80.256 },
  { iata: 'CLE', icao: 'KCLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', country: 'United States', lat: 41.405, lon: -81.854 },
  { iata: 'CVG', icao: 'KCVG', name: 'Cincinnati/Northern Kentucky International Airport', city: 'Hebron', country: 'United States', lat: 39.052, lon: -84.662 },
  { iata: 'IND', icao: 'KIND', name: 'Indianapolis International Airport', city: 'Indianapolis', country: 'United States', lat: 39.717, lon: -86.294 },
  { iata: 'CMH', icao: 'KCMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', country: 'United States', lat: 39.998, lon: -82.891 },
  { iata: 'JAX', icao: 'KJAX', name: 'Jacksonville International Airport', city: 'Jacksonville', country: 'United States', lat: 30.494, lon: -81.687 },
  { iata: 'MEM', icao: 'KMEM', name: 'Memphis International Airport', city: 'Memphis', country: 'United States', lat: 35.042, lon: -89.976 },
  { iata: 'OKC', icao: 'KOKC', name: 'Will Rogers World Airport', city: 'Oklahoma City', country: 'United States', lat: 35.393, lon: -97.600 },
  { iata: 'SAT', icao: 'KSAT', name: 'San Antonio International Airport', city: 'San Antonio', country: 'United States', lat: 29.533, lon: -98.470 },
  { iata: 'ABQ', icao: 'KABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque', country: 'United States', lat: 35.040, lon: -106.609 },
  { iata: 'ELP', icao: 'KELP', name: 'El Paso International Airport', city: 'El Paso', country: 'United States', lat: 31.807, lon: -106.377 },
  { iata: 'OMA', icao: 'KOMA', name: 'Eppley Airfield', city: 'Omaha', country: 'United States', lat: 41.303, lon: -95.894 },
  { iata: 'TUS', icao: 'KTUS', name: 'Tucson International Airport', city: 'Tucson', country: 'United States', lat: 32.116, lon: -110.941 },
  { iata: 'BNE', icao: 'YBBN', name: 'Brisbane Airport', city: 'Brisbane', country: 'Australia', lat: -27.384, lon: 153.117 },
  { iata: 'PER', icao: 'YPPH', name: 'Perth Airport', city: 'Perth', country: 'Australia', lat: -31.940, lon: 115.966 },
  { iata: 'ADL', icao: 'YPAD', name: 'Adelaide Airport', city: 'Adelaide', country: 'Australia', lat: -34.945, lon: 138.530 },
  { iata: 'CBR', icao: 'YSCB', name: 'Canberra Airport', city: 'Canberra', country: 'Australia', lat: -35.306, lon: 149.195 },
  { iata: 'CHC', icao: 'NZCH', name: 'Christchurch International Airport', city: 'Christchurch', country: 'New Zealand', lat: -43.489, lon: 172.532 },
  { iata: 'WLG', icao: 'NZWN', name: 'Wellington International Airport', city: 'Wellington', country: 'New Zealand', lat: -41.327, lon: 174.805 },
  { iata: 'MAN', icao: 'EGCC', name: 'Manchester Airport', city: 'Manchester', country: 'United Kingdom', lat: 53.353, lon: -2.274 },
  { iata: 'STN', icao: 'EGSS', name: 'London Stansted Airport', city: 'London', country: 'United Kingdom', lat: 51.885, lon: 0.235 },
  { iata: 'LTN', icao: 'EGGW', name: 'Luton Airport', city: 'London', country: 'United Kingdom', lat: 51.874, lon: -0.368 },
  { iata: 'EDI', icao: 'EGPH', name: 'Edinburgh Airport', city: 'Edinburgh', country: 'United Kingdom', lat: 55.950, lon: -3.372 },
  { iata: 'GLA', icao: 'EGPF', name: 'Glasgow Airport', city: 'Glasgow', country: 'United Kingdom', lat: 55.871, lon: -4.432 },
  { iata: 'BHX', icao: 'EGBB', name: 'Birmingham Airport', city: 'Birmingham', country: 'United Kingdom', lat: 52.453, lon: -1.748 },
  { iata: 'BRS', icao: 'EGGD', name: 'Bristol Airport', city: 'Bristol', country: 'United Kingdom', lat: 51.382, lon: -2.719 },
  { iata: 'ORY', icao: 'LFPO', name: 'Orly Airport', city: 'Paris', country: 'France', lat: 48.723, lon: 2.379 },
  { iata: 'NCE', icao: 'LFMN', name: "Nice Côte d'Azur Airport", city: 'Nice', country: 'France', lat: 43.665, lon: 7.215 },
  { iata: 'LYS', icao: 'LFLL', name: 'Lyon–Saint-Exupéry Airport', city: 'Lyon', country: 'France', lat: 45.725, lon: 5.081 },
  { iata: 'MRS', icao: 'LFML', name: 'Marseille Provence Airport', city: 'Marseille', country: 'France', lat: 43.436, lon: 5.215 },
  { iata: 'TLS', icao: 'LFBO', name: 'Toulouse–Blagnac Airport', city: 'Toulouse', country: 'France', lat: 43.635, lon: 1.363 },
  { iata: 'DUS', icao: 'EDDL', name: 'Düsseldorf Airport', city: 'Düsseldorf', country: 'Germany', lat: 51.289, lon: 6.766 },
  { iata: 'BER', icao: 'EDDB', name: 'Berlin Brandenburg Airport', city: 'Berlin', country: 'Germany', lat: 52.3667, lon: 13.5033 },
  { iata: 'HAM', icao: 'EDDH', name: 'Hamburg Airport', city: 'Hamburg', country: 'Germany', lat: 53.630, lon: 9.988 },
  { iata: 'STR', icao: 'EDDS', name: 'Stuttgart Airport', city: 'Stuttgart', country: 'Germany', lat: 48.689, lon: 9.221 },
  { iata: 'CGN', icao: 'EDDK', name: 'Cologne Bonn Airport', city: 'Cologne', country: 'Germany', lat: 50.865, lon: 7.142 },
  { iata: 'MXP', icao: 'LIMC', name: 'Milan Malpensa Airport', city: 'Milan', country: 'Italy', lat: 45.630, lon: 8.723 },
  { iata: 'LIN', icao: 'LIML', name: 'Linate Airport', city: 'Milan', country: 'Italy', lat: 45.445, lon: 9.278 },
  { iata: 'VCE', icao: 'LIPZ', name: 'Venice Marco Polo Airport', city: 'Venice', country: 'Italy', lat: 45.505, lon: 12.351 },
  { iata: 'BLQ', icao: 'LIPE', name: 'Bologna Guglielmo Marconi Airport', city: 'Bologna', country: 'Italy', lat: 44.535, lon: 11.288 },
  { iata: 'NAP', icao: 'LIRN', name: 'Naples International Airport', city: 'Naples', country: 'Italy', lat: 40.886, lon: 14.290 },
  { iata: 'AGP', icao: 'LEMG', name: 'Málaga–Costa del Sol Airport', city: 'Málaga', country: 'Spain', lat: 36.674, lon: -4.499 },
  { iata: 'PMI', icao: 'LEPA', name: 'Palma de Mallorca Airport', city: 'Palma', country: 'Spain', lat: 39.551, lon: 2.738 },
  { iata: 'ALC', icao: 'LEAL', name: 'Alicante–Elche Miguel Hernández Airport', city: 'Alicante', country: 'Spain', lat: 38.282, lon: -0.558 },
  { iata: 'TFS', icao: 'GCTS', name: 'Tenerife South Airport', city: 'Tenerife', country: 'Spain', lat: 28.044, lon: -16.572 },
  { iata: 'LPA', icao: 'GCLP', name: 'Gran Canaria Airport', city: 'Gran Canaria', country: 'Spain', lat: 27.931, lon: -15.386 },
  { iata: 'IBZ', icao: 'LEIB', name: 'Ibiza Airport', city: 'Ibiza', country: 'Spain', lat: 38.872, lon: 1.373 },
  { iata: 'ACE', icao: 'GCRR', name: 'Lanzarote Airport', city: 'Lanzarote', country: 'Spain', lat: 28.9455, lon: -13.6052 },
  { iata: 'FAO', icao: 'LPFR', name: 'Faro Airport', city: 'Faro', country: 'Portugal', lat: 37.014, lon: -7.965 },
  { iata: 'OPO', icao: 'LPPR', name: 'Porto Airport', city: 'Porto', country: 'Portugal', lat: 41.248, lon: -8.681 },
  { iata: 'AYT', icao: 'LTAI', name: 'Antalya Airport', city: 'Antalya', country: 'Turkey', lat: 36.898, lon: 30.800 },
  { iata: 'ESB', icao: 'LTAC', name: 'Esenboğa International Airport', city: 'Ankara', country: 'Turkey', lat: 40.128, lon: 32.995 },
  { iata: 'ADB', icao: 'LTBJ', name: 'Adnan Menderes Airport', city: 'İzmir', country: 'Turkey', lat: 38.292, lon: 27.156 },
  { iata: 'LCA', icao: 'LCLK', name: 'Larnaca International Airport', city: 'Larnaca', country: 'Cyprus', lat: 34.875, lon: 33.624 },
  { iata: 'PFO', icao: 'LCPH', name: 'Paphos International Airport', city: 'Paphos', country: 'Cyprus', lat: 34.718, lon: 32.485 },
  { iata: 'HER', icao: 'LGIR', name: 'Heraklion International Airport "Nikos Kazantzakis"', city: 'Heraklion', country: 'Greece', lat: 35.339, lon: 25.180 },
  { iata: 'RHO', icao: 'LGRP', name: 'Rhodes International Airport', city: 'Rhodes', country: 'Greece', lat: 36.404, lon: 28.086 },
  { iata: 'CFU', icao: 'LGKR', name: 'Corfu International Airport', city: 'Corfu', country: 'Greece', lat: 39.601, lon: 19.911 },
  { iata: 'SPU', icao: 'LDSP', name: 'Split Airport', city: 'Split', country: 'Croatia', lat: 43.538, lon: 16.298 },
  { iata: 'DBV', icao: 'LDDU', name: 'Dubrovnik Airport', city: 'Dubrovnik', country: 'Croatia', lat: 42.561, lon: 18.268 },
  { iata: 'TIV', icao: 'LYTV', name: 'Tivat Airport', city: 'Tivat', country: 'Montenegro', lat: 42.404, lon: 18.723 },
  { iata: 'BEG', icao: 'LYBE', name: 'Belgrade Nikola Tesla Airport', city: 'Belgrade', country: 'Serbia', lat: 44.818, lon: 20.309 },
  { iata: 'SOF', icao: 'LBSF', name: 'Sofia Airport', city: 'Sofia', country: 'Bulgaria', lat: 42.695, lon: 23.411 },
  { iata: 'PTY', icao: 'MPTO', name: 'Tocumen International Airport', city: 'Panama City', country: 'Panama', lat: 9.071, lon: -79.383 },
  { iata: 'SJO', icao: 'MROC', name: 'Juan Santamaría International Airport', city: 'San José', country: 'Costa Rica', lat: 9.993, lon: -84.208 },
  { iata: 'HAV', icao: 'MUHA', name: 'José Martí International Airport', city: 'Havana', country: 'Cuba', lat: 22.989, lon: -82.409 },
  { iata: 'KIN', icao: 'MKJP', name: 'Norman Manley International Airport', city: 'Kingston', country: 'Jamaica', lat: 17.935, lon: -76.787 },
  { iata: 'POS', icao: 'TTPP', name: 'Piarco International Airport', city: 'Port of Spain', country: 'Trinidad and Tobago', lat: 10.595, lon: -61.337 },
  { iata: 'GEO', icao: 'SYCJ', name: 'Cheddi Jagan International Airport', city: 'Georgetown', country: 'Guyana', lat: 6.498, lon: -58.254 },
  { iata: 'PBM', icao: 'SMJP', name: 'Johan Adolf Pengel International Airport', city: 'Paramaribo', country: 'Suriname', lat: 5.452, lon: -55.187 },
  { iata: 'CAY', icao: 'SOCA', name: 'Cayenne – Félix Eboué Airport', city: 'Cayenne', country: 'French Guiana', lat: 4.819, lon: -52.360 },
  { iata: 'GUA', icao: 'MGGT', name: 'La Aurora International Airport', city: 'Guatemala City', country: 'Guatemala', lat: 14.583, lon: -90.527 },
  { iata: 'SAL', icao: 'MSLP', name: 'Monseñor Óscar Arnulfo Romero International Airport', city: 'San Salvador', country: 'El Salvador', lat: 13.440, lon: -89.055 },
  { iata: 'TGU', icao: 'MHTG', name: 'Toncontín International Airport', city: 'Tegucigalpa', country: 'Honduras', lat: 14.060, lon: -87.217 },
  { iata: 'MGA', icao: 'MNMG', name: 'Augusto C. Sandino International Airport', city: 'Managua', country: 'Nicaragua', lat: 12.141, lon: -86.168 },
  { iata: 'BZE', icao: 'MZBZ', name: 'Philip S. W. Goldson International Airport', city: 'Belize City', country: 'Belize', lat: 17.539, lon: -88.308 },
  { iata: 'CCS', icao: 'SVMI', name: 'Simón Bolívar International Airport', city: 'Caracas', country: 'Venezuela', lat: 10.603, lon: -66.990 },
  { iata: 'UIO', icao: 'SEQM', name: 'Mariscal Sucre International Airport', city: 'Quito', country: 'Ecuador', lat: -0.113, lon: -78.357 },
  { iata: 'GYE', icao: 'SEGU', name: 'José Joaquín de Olmedo International Airport', city: 'Guayaquil', country: 'Ecuador', lat: -2.157, lon: -79.883 },
  { iata: 'LPB', icao: 'SLLP', name: 'El Alto International Airport', city: 'La Paz', country: 'Bolivia', lat: -16.513, lon: -68.192 },
  { iata: 'VVI', icao: 'SLVR', name: 'Viru Viru International Airport', city: 'Santa Cruz de la Sierra', country: 'Bolivia', lat: -17.644, lon: -63.135 },
  { iata: 'ASU', icao: 'SGAS', name: 'Silvio Pettirossi International Airport', city: 'Asunción', country: 'Paraguay', lat: -25.239, lon: -57.519 },
  { iata: 'MVD', icao: 'SUMU', name: 'Carrasco International Airport', city: 'Montevideo', country: 'Uruguay', lat: -34.838, lon: -56.029 },
  { iata: 'GIG', icao: 'SBGL', name: 'Rio de Janeiro/Galeão International Airport', city: 'Rio de Janeiro', country: 'Brazil', lat: -22.809, lon: -43.250 },
  { iata: 'CGH', icao: 'SBSP', name: 'São Paulo/Congonhas Airport', city: 'São Paulo', country: 'Brazil', lat: -23.626, lon: -46.656 },
  { iata: 'BSB', icao: 'SBBR', name: 'Brasília International Airport', city: 'Brasília', country: 'Brazil', lat: -15.871, lon: -47.918 },
  { iata: 'CNF', icao: 'SBCF', name: 'Tancredo Neves International Airport', city: 'Belo Horizonte', country: 'Brazil', lat: -19.624, lon: -43.971 },
  { iata: 'SSA', icao: 'SBSV', name: 'Salvador International Airport', city: 'Salvador', country: 'Brazil', lat: -12.910, lon: -38.331 },
  { iata: 'REC', icao: 'SBRF', name: 'Recife/Guararapes–Gilberto Freyre International Airport', city: 'Recife', country: 'Brazil', lat: -8.126, lon: -34.922 },
  { iata: 'FOR', icao: 'SBFZ', name: 'Fortaleza-Pinto Martins International Airport', city: 'Fortaleza', country: 'Brazil', lat: -3.776, lon: -38.532 },
  { iata: 'POA', icao: 'SBPA', name: 'Salgado Filho International Airport', city: 'Porto Alegre', country: 'Brazil', lat: -29.993, lon: -51.171 },
  { iata: 'CWB', icao: 'SBCT', name: 'Afonso Pena International Airport', city: 'Curitiba', country: 'Brazil', lat: -25.528, lon: -49.175 },
  { iata: 'MAO', icao: 'SBEG', name: 'Eduardo Gomes International Airport', city: 'Manaus', country: 'Brazil', lat: -3.038, lon: -60.049 },
  { iata: 'BFS', icao: 'EGAA', name: 'Belfast International Airport', city: 'Belfast', country: 'United Kingdom', lat: 54.6575, lon: -6.2158 },
  { iata: 'BHD', icao: 'EGAC', name: 'George Best Belfast City Airport', city: 'Belfast', country: 'United Kingdom', lat: 54.6181, lon: -5.8725 }
];